import { TelegramBot, UpdateType } from "https://raw.githubusercontent.com/michael-spengler/deno-telegram-bot-api/master/mod.ts"
import "https://deno.land/x/dot_env@0.2.0/load.ts"
import { Request } from 'https://deno.land/x/request@1.3.2/mod.ts'

const TOKEN = Deno.env.get("TOKEN");
if (!TOKEN) throw new Error("Bot token is not provided");
const bot = new TelegramBot(TOKEN);
var data_json = new String()
data_json = await Request.get('https://raw.githubusercontent.com/Qusay99/security-alert-for-safety/Telegram-Bot-Developement/location_to_chat_IDs.json')

bot.on(UpdateType.Message, async (message: any) => {

    const location = "Köln"
    var chatID = ""
    var emergency_message = "[NOTFALLNACHRICHT] - [NAME] hat auf den Notfall-Knopf gedrückt.\nDie Person befindet sich bei den Koordinaten X / Y"

    for (let prop in data_json) {
        let entry = data_json[prop]
        if (Object.values(entry).includes(location)) {
            chatID = Object.values(entry)[2]
        }
    }

    await bot.sendMessage({ chat_id: chatID, text: `${emergency_message} \n(Test-Message generated by SafetyBot ${location})` })

});

bot.run({
    polling: true,
});